#+TITLE: Blanket
#+STARTUP: showall

[[Made for Emacs 25.3+][https://img.shields.io/badge/Made_for-Emacs_25.3+-blueviolet.svg?style=for-the-badge]] [[Made for Emacs 25.3+][https://img.shields.io/badge/Version-Beta-blue.svg?style=for-the-badge]]

Blanket is an interface to the Picnic development commands, implemented
as an Emacs package.

* Why Blanket?
  Either it is a romantic picnic or family picnic, we need something
  to sit on and be productive and picnic blacket is the best option
  for that. Otherwise, people can choose to stand or sit on the grass.

* Prerequisites
  - [[https://github.com/magit/transient][transient]]
  - [[https://github.com/purcell/exec-path-from-shell][exec-path-from-shell]]
  - [[https://orgmode.org/][org-mode]]
  - [[https://github.com/Kungsgeten/yankpad][yankpad]] [Optional for snippets]

* Getting started
  Load [[file:blanket.el][blanket.el]] in your .emacs file.
  #+begin_src elisp
    (load-file "<path-to-dotfiles/blanket/blanket.el")
  #+end_src

  To try Blanket, just call ~M-x~ ~blanket~. This will show the top
  level menu for Picnic commands. ~M-o~ is recommended as a hokey for
  blanket menu if you are using dvorak keyboard:

  #+begin_src elisp
    (global-set-key (kbd "M-o") 'blanket)
  #+end_src

** Migration
  Quickly create a migration and then apply or undo it from the
  blanket menu.

  
** Testing
  Quickly run a unit test by going into the test file and run it from
  the blanket menu.
